spring.application.name=Sistema_Notas

spring.datasource.url=jdbc:mysql://localhost:3306/notas_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

server.port=8080
